'use strict';

(function () {
  var PIN_WIDTH = 65;
  var PIN_HEIGHT = 65;
  var PIN_TAIL = 19;
  var OBJECT_COUNT = 5;
  var DEFAULT_TOP_MAIN_PIN = 375;
  var DEFAULT_LEFT_MAIN_PIN = 570;

  window.data = {
    PIN__WIDTH: PIN_WIDTH,
    PIN__HEIGHT: PIN_HEIGHT,
    PIN__TAIL: PIN_TAIL,
    OBJECT_COUNT: OBJECT_COUNT,
    DEFAULT__TOP__MAIN__PIN: DEFAULT_TOP_MAIN_PIN,
    DEFAULT__LEFT__MAIN__PIN: DEFAULT_LEFT_MAIN_PIN
  };
})();
